### ISSUE TITLE
Feedback zur dritten Pflichtübung

### ISSUE THREAD

**Issue by 1233334** [tpe-lecture/repo-08#3]
Gruppe 08
•	(-5) setKorrupt bei Richter nicht korrekt, da Richter nicht seine Korruptheit wechseln kann
•	(-5) kaempfe-Methode sollte ein bool-Wert zurückgeben
•	(-5) Klasse Metropolis ist leer, dabei hat Metropolis Einwohner, Unternhemen usw.

Summe: 85

**Comment by iinnaann** [comment]
Hallo,

-setKorrupt: Ist private, daher kann die Korruptheit nicht geändert werden oder haben wird da etwas übersehen? In der Vorlessung wurde uns gesagt wir sollen die Getter/Setter Methoden zuerst private erstellen und wenn wir es benötigen nach aussen öffnen.

-kaempfe Methode: Da uns kein Datentyp vorgeschrieben worden ist, haben wir auch keinen bool-Wert zurückgegeben.

Beste Grüße

**Comment by 1233334** [comment]
ok, setKorrupt Methode ist private, das stimmt, aber die brauch man hier nicht, also wäre diese hier überflüssig (trotzdem -5) :)
wegen kaempfe-Methode muss ich es mit Herr Smits morgen besprechen, weil eigentlich würden wir gerne auch Testen, ob die Methode funktioniert, und die Methode ist ja in eurem Testfall nicht vorhanden,

**Comment by 1233334** [comment]
(+5) nachc Absprache mit Herr Smits wegen kampfe-Methode
neue Summe: 90
